---
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hawthorne-notifications-frontend
    environment:
      - REACT_APP_BACKEND_BASE_URL=http://backend:8080
      - REACT_APP_FRONTEND_BASE_URL=http://localhost:3000
    ports:
      - "3000:3000"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
        reservations:
          cpus: '0.25'
          memory: 128M
    depends_on:
      - backend
    networks:
      - net

  backend:
    image: hawthorne-notifications-app:latest
    restart: unless-stopped
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/run/secrets/GOOGLE_APPLICATION_CREDENTIALS
      - GMAIL_PASSWORD=${GMAIL_PASSWORD}
      - env=dev
    secrets:
      - GOOGLE_APPLICATION_CREDENTIALS
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
        reservations:
          cpus: '0.25'
          memory: 128M
    networks:
      - net

secrets:
  GOOGLE_APPLICATION_CREDENTIALS:
    file: $HOME/.gcloud/hawthorne-notifications-0a1c3d137ad2.json

networks:
  net:
    driver: bridge
